name: motogp_apk
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: any

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true


  assets:
     - img/logo1.png
     - img/contoh1.png
     - img/news1.jpg
     - img/news2.jpg
     - img/news3.jpg
     - img/news4.jpg
     - img/news5.jpg
     - img/news6.jpg
     - img/news7.jpg
     - img/news8.jpg
     - img/news9.jpg
     - img/news10.jpg
     - img/TEST.png
     - img/marc.jpg
     - img/marc2.jpg
     - img/marc3.jpg
     - img/04 Dovi.png
     - img/5 Zarco.png
     - img/9 Petrucci.png
     - img/12 Vinales.png
     - img/17 Abraham.png
     - img/20 Quartararo.png
     - img/21 Morbidelli.png
     - img/29 Iannone.png
     - img/30 Nakagami.png
     - img/35 Crutchlow.png
     - img/36 Mir.png
     - img/41 Espargaro.png
     - img/42 Rins.png
     - img/43 Miller.png
     - img/44 Espargaro.png
     - img/46 Rossi.png
     - img/53 Rabat.png
     - img/55 Syahrin.png
     - img/63 Bagnaia.png
     - img/82 Kallio.png
     - img/88 Oliveira.png
     - img/93 Marquez.png
     - img/99 Lorenzo.png
     - img/1 Losail Qatar.png
     - img/2 Termas de Rio Hondo Argentina.png
     - img/3 Cota America.png
     - img/4 Jerez Spain.png
     - img/5 Le Mans Prancis.png
     - img/6 Mugello Italia.png
     - img/7 Catalunya Catalunya.png
     - img/8 Assen Belanda.png
     - img/9 Sachsenring Jerman.png
     - img/10 Brno Republik Ceko.png
     - img/11 Red Bull Ring Austria.png
     - img/12 Silverstone Inggris Raya.png
     - img/13 Misano San Marino.png
     - img/14 Aragon Aragon.png
     - img/15 Buriram Thailand.png
     - img/16 Motegi Jepang.png
     - img/17 Phillip Island Australia.png
     - img/18 Sepang Malaysia.png
     - img/19 Valencia.png
     - img/001 Losail Qatar.png
     - img/coba.png
     - img/clogo.png
     - img/ilogo.png
     - img/rlogo.png
     - img/tlogo.png
     - img/0001.png
     - img/0002.png
     - img/0003.png
     - img/0004.png
     - img/0005.png
     - img/0006.png
     - img/0007.png
     - img/0008.png
     - img/0009.png
     - img/0010.png
     - img/0011.png
     - img/0012.png
     - img/0013.png
     - img/0014.png
     - img/0015.png
     - img/0016.png
     - img/0017.png
     - img/0018.png
     - img/0019.png
     - img/end.jpg
     - img/berita1.jpg
     - img/berita2.jpg
     - img/berita3.jpg
     - img/berita4.jpg
     - img/berita5.jpg
     - img/berita6.jpg
     - img/berita7.jpg
     - img/berita8.jpg
     - img/berita9.jpg
     - img/berita10.jpg
     - img/Berita01.jpeg




  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
